/*
 * This file is autogenerated from gen_mlp_onnx.py.
 * DO NOT EDIT.
 */

#pragma once

#define k_onnx_model_a_input_tensors 1
#define k_onnx_model_a_input_size 10
#define k_onnx_model_a_output_size 2


OMTensorList *
run_main_graph_model_a(OMTensorList *);
